### ISSUE TITLE
Logo in header

### ISSUE THREAD

**Issue by RackhamLeNoir** [aaronwolen/pandoc-letter#16]
Hi,

This template is great, and very useful. It would be even greater with the possibility to include a logo in the header for corporate mail. Is it in the plans?

**Comment by RackhamLeNoir** [comment]
OK, used letterhead. Sorry for disturbance.

There is no equivalent for footer though (with the possibility to keep in on every page).

**Comment by aaronwolen** [comment]
True, you can only insert graphics into the header. Glad you got it worked out 👍
