### ISSUE TITLE
links-as-notes should be enabled by default

### ISSUE THREAD

**Issue by aaronwolen** [aaronwolen/pandoc-letter#17]

**Comment by adunning** [comment]
I would vote for leaving it as-is; any changes to the base template add more complexity, and the option is well documented. (But would be interested if there is a rationale I am missing.)

**Comment by aaronwolen** [comment]
Yeah, I've changed my mind. This came up because the template was included in an [R package](https://cran.r-project.org/web/packages/linl) and there was a desire to make nicer looking defaults that require less fiddling by the user. I've decided to make those convenience changes specific to the R version and keep this version as close as possible to Pandoc's template.
