### ISSUE TITLE
pandoc 2.17 has changed the way babel handles fonts; can the letter template be update please?

### ISSUE THREAD

**Issue by kleinbottle** [aaronwolen/pandoc-letter#34]
On occasion, I mix both the Latin and a non-Latin script in letters. `pandoc 2.17` has spruced the way this is handled by using `babel` for both `lualatex` and `xelatex`. I wonder if you would consider refreshing the template to keep up with changes.

Thanks.

**Comment by aaronwolen** [comment]
Hey @kleinbottle, thanks for posting! I'm not familiar with the changes you referenced and not sure what needs to be updated, but PRs are always welcome.
