### ISSUE TITLE
Recipient address(es) on the right

### ISSUE THREAD

**Issue by Enrico68** [aaronwolen/pandoc-letter#6]
Hello Aron,

thanks for your template (it provides me a super fast way of writing letter together with few macros in VIM). I just wanted to ask you if it is possible to modify it in order to get the recipient address on the right an return on the left (italian ways of writing letter ..!) ...

**Comment by aaronwolen** [comment]
The template doesn't currently provide such an option but I'm not opposed to adding it. I'd like to see if @adunning has any thoughts about implementing it. My best guess is it would require redefining the letter class's `\opening` function.

**Comment by adunning** [comment]
Sorry not to have responded earlier: to get more advanced options, you're likely best off using the scrlttr2 class. There's a Pandoc version of it at <https://github.com/JensErat/pandoc-scrlttr2>.

**Comment by Enrico68** [comment]
Andrew Dunning <notifications@github.com> writes:

> Sorry not to have responded earlier: to get more advanced options, you're likely best off using the scrlttr2 class. There's a Pandoc version of it at <https://github.com/JensErat/pandoc-scrlttr2>.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/aaronwolen/pandoc-letter/issues/6#issuecomment-225834310

ok. thanks
