### ISSUE TITLE
license

### ISSUE THREAD

**Issue by ddavidebor** [aaronwolen/pandoc-letter#7]
Hi, what's the license for this repo?

Davide

**Comment by aaronwolen** [comment]
Since it's a light modification of a Pandoc template, it's probably most appropriate to inherit the pandoc-templates license, actually a dual license: 

> All of the templates in this repository are dual licensed, under both the GPL (v2 or higher, same as pandoc) and the BSD 3-clause license (included below).

I'll make a note in the repo.

**Comment by ddavidebor** [comment]
Thank you very much
